name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_redux: ^0.7.0
  freezed_annotation: ^0.12.0
  redux_epics: ^0.14.0
  rxdart: ^0.24.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  redux: ^4.0.0+3
  http: ^0.12.2
  unit_converter: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  built_value_generator: any
  freezed: any

flutter:
  uses-material-design: true

